"""user change refresh_token nullable=True

Revision ID: 9d2beb21696d
Revises: bc95a67c35a4
Create Date: 2024-10-03 12:17:49.363864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2beb21696d'
down_revision: Union[str, None] = 'bc95a67c35a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
