"""kittens add column name

Revision ID: 8aabcbdf89fd
Revises: 9d2beb21696d
Create Date: 2024-10-03 13:42:16.152166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aabcbdf89fd'
down_revision: Union[str, None] = '9d2beb21696d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kittens', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('kittens', 'name')
    # ### end Alembic commands ###
